const paths = {
 'arrow-right':'<path d="M4 12h15m-6-6 6 6-6 6"/>',
 'arrow-left':'<path d="M20 12H5m6-6-6 6 6 6"/>',
 'arrow-down':'<path d="M12 4v15m-6-6 6 6 6-6"/>',
 search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 4.5 4.5"/>',
 heart:'<path d="M20.5 5.5a5.1 5.1 0 0 0-7.2 0L12 6.8l-1.3-1.3a5.1 5.1 0 0 0-7.2 7.2L12 21l8.5-8.3a5.1 5.1 0 0 0 0-7.2Z"/>',
 sparkle:'<path d="M12 2c0 7-3 10-10 10 7 0 10 3 10 10 0-7 3-10 10-10-7 0-10-3-10-10Z"/><path d="M20 2v4m-2-2h4M3 19v3m-1.5-1.5h3"/>',
 flower:'<path d="M12 20C3 20 0 13 3 9c4 0 7 4 9 11Zm0 0c9 0 12-7 9-11-4 0-7 4-9 11Zm0 0C5 14 6 6 12 2c6 4 7 12 0 18Z"/>',
 pin:'<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',
 whatsapp:'<path d="M20.5 11.5a9 9 0 0 1-13.2 8L2 21l1.5-5.3A9 9 0 1 1 20.5 11.5Z"/><path d="M8 7c-2 3 3 8 6 8l2-2-3-1-1 1c-1-.5-2-1.5-2-2l1-1-1-3H8Z"/>',
 menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',
 close:'<path d="m6 6 12 12M6 18 18 6"/>',
 calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 10h18m-13 4h1m3 0h1m3 0h1m-9 3h1m3 0h1"/>'
};
const icon = (name) => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${paths[name] || paths.sparkle}</svg>`;
function renderIcons(root=document){root.querySelectorAll('[data-icon]').forEach(el=>el.outerHTML=icon(el.dataset.icon));}
renderIcons();
const collections = [
 {id:'kantha',name:'The Kantha edit',image:'kantha',tag:'THE ART OF THE STITCH',subtitle:'Patient hands. Extraordinary details.',description:'Discover the beauty of Bengalâ€™s Kantha tradition and detailed handwork. A celebration of patient stitches, thoughtful design, and the artisans behind every piece.',keywords:'blue teal embroidery stitch handwork kantha cotton',meta:'Kantha & handwork',note:'A detail from Kinnoriâ€™s collection. Enquire for the current Kantha designs and fabric options.'},
 {id:'tussar',name:'Tussar, timeless',image:'tussar',tag:'LOVED BY OUR COMMUNITY',subtitle:'An effortless kind of elegance.',description:'Light, graceful, and full of character. Explore Tussar silk sarees that bring the beauty of Bengal into your everyday celebrations. Pictured: a Kinnori customer wearing her treasured saree.',keywords:'red pink tussar tusser silk breathable customer',meta:'Tussar silk',note:'Customer photograph shared by Kinnori. Ask us about available colours and designs.'},
 {id:'silk',name:'Silks of Bengal',image:'silk',tag:'FOR YOUR SPECIAL MOMENTS',subtitle:'Heritage woven into every occasion.',description:'From Murshidabad silk to Kantha on Bishnupur silk, discover a little of Bengalâ€™s rich textile heritage. Sarees for festive gatherings, meaningful gifts, and moments worth remembering.',keywords:'yellow gold bengal murshidabad bishnupur pujo silk festive hand painted',meta:'Bengal silks',note:'Photograph from a Kinnori exhibition. The pictured saree is inspiration; exact availability is confirmed by Debadrita.'}
];
let saved = [];
try { saved=JSON.parse(localStorage.getItem('kinnori-favourites')||'[]'); if(!Array.isArray(saved))saved=[]; saved=saved.filter(id=>collections.some(c=>c.id===id)); } catch { saved=[]; }
let filter='all';
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function card(c){return `<article class="collection-card"><div class="card-photo ${c.id}"><button class="image-button" data-detail="${c.id}" aria-label="Explore ${c.name}"><img src="./images/${c.image}.jpg" alt="${c.id==='kantha'?'Blue saree with delicate white stitching and Kinnori packaging':c.id==='tussar'?'Kinnori customer wearing a red Tussar silk saree':'A golden-yellow saree worn at a Kinnori exhibition'}" loading="lazy"></button><span class="card-tag">${c.tag}</span><button class="save-button ${saved.includes(c.id)?'saved':''}" data-save="${c.id}" aria-label="${saved.includes(c.id)?'Remove':'Save'} ${c.name} ${saved.includes(c.id)?'from':'to'} favourites" aria-pressed="${saved.includes(c.id)}">${icon('heart')}</button><button class="card-explore" data-detail="${c.id}" aria-label="View ${c.name}">${icon('arrow-right')}</button></div><div class="card-content"><div><h3><a href="#collections" data-detail="${c.id}">${c.name}</a></h3><p>${c.subtitle}</p></div><button class="card-enquire" data-enquire="${c.id}">Enquire â†—</button></div></article>`;}
function renderCollections(){const shown=filter==='all'?collections:collections.filter(c=>c.id===filter);document.querySelector('#collection-grid').innerHTML=shown.map(card).join('');}
function updateSaved(){try{localStorage.setItem('kinnori-favourites',JSON.stringify(saved));}catch{}const count=document.querySelector('#saved-count');count.textContent=saved.length;count.hidden=!saved.length;document.querySelectorAll('[data-save]').forEach(btn=>{let yes=saved.includes(btn.dataset.save),c=collections.find(c=>c.id===btn.dataset.save);btn.classList.toggle('saved',yes);btn.setAttribute('aria-pressed',String(yes));btn.setAttribute('aria-label',`${yes?'Remove':'Save'} ${c.name} ${yes?'from':'to'} favourites`);});}
let toastTimeout;
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>el.classList.remove('show'),2600);}
document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{filter=button.dataset.filter;document.querySelectorAll('.filter').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));});renderCollections();}));
const overlay=document.querySelector('#modal-overlay');const modal=overlay.querySelector('.modal');const content=document.querySelector('#modal-content');let previousFocus=null;let modalType='';
function openModal(html,type){if(overlay.hidden)previousFocus=document.activeElement;content.innerHTML=html;modalType=type;overlay.hidden=false;document.body.classList.add('modal-open');modal.scrollTop=0;renderIcons(content);requestAnimationFrame(()=>{const focus=content.querySelector('[autofocus]');(focus||modal).focus();});}
function closeModal(){overlay.hidden=true;document.body.classList.remove('modal-open');modalType='';if(previousFocus?.isConnected)previousFocus.focus();}
overlay.querySelector('.modal-close').addEventListener('click',closeModal);
overlay.addEventListener('click',e=>{if(e.target===overlay)closeModal();});
document.addEventListener('keydown',e=>{if(overlay.hidden)return;if(e.key==='Escape')closeModal();if(e.key==='Tab'){const focusable=[...modal.querySelectorAll('a[href],button:not([disabled]),input,select,textarea,[tabindex="0"]')].filter(e=>!e.hidden&&e.getClientRects().length);const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===modal)){last?.focus();e.preventDefault();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===modal)){first?.focus();e.preventDefault();}}});
function detail(id){const c=collections.find(c=>c.id===id);if(!c)return;openModal(`<div class="product-detail"><img src="./images/${c.image}.jpg" alt="${c.name}"><div><span class="eyebrow">THE KINNORI SAREE EDIT</span><h2 id="modal-title">${c.name}</h2><p>${c.description}</p><div class="detail-meta"><span>${c.meta}</span><span>Price on enquiry</span></div><button class="button primary" data-enquire="${c.id}">Enquire about this edit ${icon('arrow-right')}</button><button class="button" data-save="${c.id}" aria-pressed="${saved.includes(c.id)}">${icon('heart')} ${saved.includes(c.id)?'Saved to favourites':'Save to favourites'}</button><p class="detail-disclaimer">${c.note}</p></div></div>`,'detail');}
function enquiry(id){const c=collections.find(c=>c.id===id);openModal(`<span class="eyebrow">A PERSONAL SHOPPING EXPERIENCE</span><h2 id="modal-title">Letâ€™s find your <em>forever saree.</em></h2><p>Share a little about what youâ€™re looking for. Your message will open in WhatsApp, ready to send directly to Debadrita.</p><form class="enquiry-form" id="enquiry-form"><div class="form-row"><label>Your name<input name="name" placeholder="How shall we call you?" maxlength="80" required autocomplete="given-name"></label><label>Which edit caught your eye?<select name="collection">${collections.map(x=>`<option value="${x.id}" ${x.id===c?.id?'selected':''}>${x.name}</option>`).join('')}<option value="all" ${!c?'selected':''}>Iâ€™d love some guidance</option></select></label></div><label>A little about your perfect saree<textarea name="message" placeholder="Your occasion, favourite colours, budget, or any questionsâ€¦" maxlength="1500"></textarea></label><button class="button primary" type="submit">Continue to WhatsApp ${icon('whatsapp')}</button><p class="detail-disclaimer">Nothing is sent until you press send in WhatsApp. Prices, availability, payment, and delivery are confirmed personally by Kinnori.</p></form>`,'enquiry');document.querySelector('#enquiry-form').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const name=String(fd.get('name')).trim();if(!name){e.currentTarget.elements.name.setCustomValidity('Please enter your name.');e.currentTarget.elements.name.reportValidity();return;}const selected=collections.find(x=>x.id===fd.get('collection'));const message=`Hi Debadrita! Iâ€™m ${name}. Iâ€™m interested in ${selected?selected.name:'exploring Kinnoriâ€™s sarees'}.
${String(fd.get('message')).trim()}
Could you please share the available designs and prices?`;window.open(`https://wa.me/61478551277?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer');});document.querySelector('[name="name"]').addEventListener('input',e=>e.target.setCustomValidity(''));}
function savedItem(c){return `<div class="saved-item"><img src="./images/${c.image}.jpg" alt="${c.name}"><div><h3>${c.name}</h3><button data-detail="${c.id}">Explore this edit â†—</button></div><button class="icon-btn" data-remove="${c.id}" aria-label="Remove ${c.name}">${icon('close')}</button></div>`;}
function savedModal(){openModal(`<span class="eyebrow">PIECES THAT SPEAK TO YOU</span><h2 id="modal-title">Your little <em>love list.</em></h2><div class="saved-list">${saved.length?collections.filter(c=>saved.includes(c.id)).map(savedItem).join(''):`<div class="empty-state">${icon('heart')}<h3>A beautiful story starts here.</h3><p>Tap the heart on an edit to save it for another look.</p><button class="button primary" data-browse>Explore the saree edit ${icon('arrow-right')}</button></div>`}</div>${saved.length?'<p class="detail-disclaimer">Your favourites are saved on this device. Enquire with Debadrita for current sarees and prices.</p>':''}`,'saved');}
function searchResults(query){const q=query.toLowerCase().trim();const results=collections.filter(c=>`${c.name} ${c.keywords}`.toLowerCase().includes(q));document.querySelector('#search-results').innerHTML=results.length?results.map(c=>`<div class="saved-item"><img src="./images/${c.image}.jpg" alt="${c.name}"><div><h3>${c.name}</h3><button data-detail="${c.id}">Explore this edit â†—</button></div></div>`).join(''):`<div class="empty-state"><h3>No matching edits just yet.</h3><p>Try â€œsilkâ€, â€œKanthaâ€, or a colour like â€œblueâ€.<br>For something specific, Debadrita is happy to help.</p><button class="text-link" data-enquire="all">Ask Debadrita â†—</button></div>`;}
document.querySelector('#search-open').addEventListener('click',()=>{openModal(`<span class="eyebrow">FIND SOMETHING BEAUTIFUL</span><h2 id="modal-title">What speaks to <em>you?</em></h2><label class="search-field">${icon('search')}<input type="search" id="collection-search" placeholder="Try silk, Kantha, or a colourâ€¦" aria-label="Search collections" autofocus autocomplete="off"></label><p class="search-hint">EXPLORE OUR COLLECTION EDITS</p><div id="search-results" aria-live="polite"></div>`,'search');searchResults('');document.querySelector('#collection-search').addEventListener('input',e=>searchResults(e.target.value));});
document.querySelectorAll('.saved-open').forEach(btn=>btn.addEventListener('click',savedModal));
document.addEventListener('click',e=>{const detailBtn=e.target.closest('[data-detail]');if(detailBtn){e.preventDefault();detail(detailBtn.dataset.detail);return;}const enquire=e.target.closest('[data-enquire]');if(enquire){enquiry(enquire.dataset.enquire);return;}const save=e.target.closest('[data-save]');if(save){const id=save.dataset.save;if(saved.includes(id)){saved=saved.filter(x=>x!==id);toast('Removed from your love list');}else{saved.push(id);toast('A little love, saved for later');}updateSaved();if(modalType==='detail')save.innerHTML=`${icon('heart')} ${saved.includes(id)?'Saved to favourites':'Save to favourites'}`;return;}const remove=e.target.closest('[data-remove]');if(remove){saved=saved.filter(x=>x!==remove.dataset.remove);updateSaved();savedModal();toast('Removed from your love list');return;}if(e.target.closest('[data-browse]')){closeModal();document.querySelector('#collections').scrollIntoView({behavior:'smooth'});}});
document.querySelector('#how-to-order').addEventListener('click',()=>{openModal(`<span class="eyebrow">PERSONAL, FROM THE VERY FIRST THREAD</span><h2 id="modal-title">A saree. <em>A conversation.</em></h2><ol class="order-steps"><li><h3>Find your inspiration</h3><p>Browse our edits and save what you love. Each photograph is a glimpse of Kinnori, not a live stock listing.</p></li><li><h3>Say hello to Debadrita</h3><p>Enquire on WhatsApp or email. Weâ€™ll share currently available designs, details, and prices, and help with your questions.</p></li><li><h3>Make it yours</h3><p>Confirm your choice, payment arrangements, and delivery or viewing options directly with Kinnori before placing your order.</p></li></ol><button class="button primary" data-enquire="all">Start a conversation ${icon('whatsapp')}</button><p class="detail-disclaimer">Prefer email? <a href="mailto:hellokinnori@outlook.com"><u>hellokinnori@outlook.com</u></a></p>`,'order');});
document.querySelector('#exhibitions-open').addEventListener('click',()=>{openModal(`<span class="eyebrow">KINNORI, IN PERSON</span><h2 id="modal-title">Come for the sarees.<br><em>Stay for the stories.</em></h2><p>We love meeting our community at Melbourne exhibitions and celebrations â€” a chance to feel the fabrics and hear the stories behind them.</p><div class="event-box">${icon('calendar')}<h3>Exhibitions & community events</h3><p>Upcoming dates and venues are shared on our Facebook page. Check our latest posts, or ask Debadrita where you can find Kinnori next.</p></div><a class="button primary" href="https://www.facebook.com/kinnoriboutique.au/" target="_blank" rel="noopener">See the latest on Facebook â†—</a><p class="detail-disclaimer">Based in Southbank, Melbourne, VIC 3006. Contact us to enquire about a viewing.</p>`,'events');});
const reviews=[{quote:'â€œThey have such a lovely collection, with each saree carrying its own charm and character. The intricate detailing and beautiful craftsmanship really stood out to me.â€',source:'A Kinnori customer Â· Google review'},{quote:'â€œThis is the first time Iâ€™ve found such beautiful Bengali sarees in Melbourne that truly capture the essence of rural Bengal and bring that traditional charm right into the heart of the city.â€',source:'A Kinnori customer Â· Google review'},{quote:'â€œBought this saree from Kinnori, Tusser Silk. Saree is light weight & breathable at reasonable price.â€',source:'Prerona Sinha Â· Shared on Facebook'}];
let reviewIndex=0;function renderReview(){const r=reviews[reviewIndex];document.querySelector('.stars').style.visibility=reviewIndex===2?'hidden':'visible';document.querySelector('#review-quote').textContent=r.quote;document.querySelector('#review-source').textContent=r.source;document.querySelector('#review-dots').innerHTML=reviews.map((r,i)=>`<button data-review="${i}" class="${i===reviewIndex?'active':''}" aria-label="Show review ${i+1}" aria-pressed="${i===reviewIndex}"></button>`).join('');}
document.querySelector('#review-prev').addEventListener('click',()=>{reviewIndex=(reviewIndex+reviews.length-1)%reviews.length;renderReview();});document.querySelector('#review-next').addEventListener('click',()=>{reviewIndex=(reviewIndex+1)%reviews.length;renderReview();});document.querySelector('#review-dots').addEventListener('click',e=>{const btn=e.target.closest('[data-review]');if(btn){reviewIndex=Number(btn.dataset.review);renderReview();}});
const menu=document.querySelector('#menu-toggle'),nav=document.querySelector('.header nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation');menu.innerHTML=icon(open?'close':'menu');});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation');menu.innerHTML=icon('menu');}));
renderCollections();updateSaved();renderReview();

